### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found 

### ISSUE THREAD

**Issue by dumbelldore** [bair-climate-initiative/scale-mae#11]
I'm trying to run evaluation only, I get the following error:
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/user/miniconda/envs/scalemae/lib/python3.9/site-packages/pyproj/../../../libproj.so.25)

**Comment by RitwikGupta** [comment]
@dumbelldore This sounds like an environment issue. Make sure you have build tools installed in your Linux distro.
