### ISSUE TITLE
Question about GSDPE

### ISSUE THREAD

**Issue by wolfilip** [bair-climate-initiative/scale-mae#14]
Greetings!

After having looked at the code and debugged it, I couldn't find the part where image GSD is used. In the paper you state that g/G is used in the sin and cos functions for positional embeddings, but I could only find G used, which is a constant with default value 1. I understand that you use image resolution and cropping to get the scale values. Could you please help me find the code snippet where image GSD is used? Thanks in advance.

**Comment by wolfilip** [comment]
Okay so i figured it out, GSD is simulated through different resolution scalings.

**Comment by maneeshsistla8** [comment]
Hi @wolfilip, did you understand how exactly it is simulated? I believe the res variable is passed as gsd_ratio * (224 / eval_scale) but how is the GSD of the images in the dataset accounted for? Two images can have the same res but different GSD right

**Comment by filipwolf** [comment]
Hi @maneeshsistla8, so as far as I understand, the actual GSD of the images is never taken into account. You may have noticed that the dataset is scaled to 224x224 before training anyways. So all the method tries to do is simulate GSD by inputting the same image at multiple resolutions, thereby simulating a different GSD. This is unfortunately not that clear in the paper, as the paper constantly refers to real GSD. Fortunately, in the fmow dataset, most images have a fairly similar GSD anyways. I am of course not the author of the paper, but this is what I gathered from the code.
