### ISSUE TITLE
Why other backbone architectures were not used?

### ISSUE THREAD

**Issue by fazlicodes** [bair-climate-initiative/scale-mae#9]
Is there a reason for not using other backbone architecture like:
-ViT_B-32
-ViT_B-16
-ResNet Architectures

**Comment by RitwikGupta** [comment]
We provided comparisons to ViT-L since that is what prior work used.
CNNs like ResNet do not utilize positional encodings. The GSDPE is one of the main contributions for Scale-MAE and is only relevant for transformers.
